### ISSUE TITLE
Administrative tools bar is breaking the layout

### ISSUE THREAD

**Issue by tauil** [call4paperz/call4paperz#198] opened 2017-04-06 23:57 UTC
## With Administrative bar:
![screenshot from 2017-04-06 20-50-16](https://cloud.githubusercontent.com/assets/14328/24780146/7b70b81a-1b0b-11e7-9b6e-4d427ae6cda1.png)

## Without Administrative bar
![screenshot from 2017-04-06 20-56-30](https://cloud.githubusercontent.com/assets/14328/24780166/9446c5fa-1b0b-11e7-9436-c862fafa6173.png)

**Comment by lucianosousa** [comment] 2017-04-10 01:44
@tauil couldn't reproduce here.
Chrome on Macbook Air 11''

**Comment by tauil** [comment] 2017-04-10 16:31
Same problem here running on a MacBook Pro (13-inch, Late 2016) in Google Chrome version 56.0.2924.87 (64-bit).

**You must be logged and owner of an event.**

Take a look at my screenshots:
<img width="1440" alt="screen shot 2017-04-10 at 13 28 39" src="https://cloud.githubusercontent.com/assets/14328/24871950/e06b7c30-1df1-11e7-9240-91164aa35982.png">

<img width="1440" alt="screen shot 2017-04-10 at 13 28 43" src="https://cloud.githubusercontent.com/assets/14328/24871970/ecf7d55c-1df1-11e7-937b-3e9c445c2fc1.png">

**Comment by lucianosousa** [comment] 2017-04-10 18:42
assign to: @tauil  ;)

**Comment by tauil** [comment] 2017-04-10 19:28
![](http://replygif.net/i/1127.gif)

**Comment by lucianosousa** [comment] 2017-10-18 23:04
@tauil any news?

**Comment by tauil** [comment] 2017-10-18 23:36
![](https://i.giphy.com/l4HnKwiJJaJQB04Zq.gif)

I'll take a look on it tomorrow.

**Comment by tauil** [comment] 2017-10-19 21:28
Here it is: https://github.com/call4paperz/call4paperz/pull/210

**Closed** 2017-10-25 21:59 UTC
Labels: bug
