### ISSUE TITLE
E-mail doesn't save / appear in user profile form

### ISSUE THREAD

**Issue by igorsantos07** [call4paperz/call4paperz#112] opened 2015-10-08 15:35 UTC
Editing your profile will show you a form without the email filled in, even though you have saved it before.

**Comment by igorsantos07** [comment] 2015-10-08 15:36
Actually, that doesn't enable me to submit a proposal, as I need to have a complete profile first. Maybe that's a bug with my user?

**Comment by fnando** [comment] 2015-10-13 17:20
I'm having the same problem. :/

**Comment by lucianosousa** [comment] 2015-10-13 17:27
Did u guys create an account with twitter?

**Comment by fnando** [comment] 2015-10-13 17:28
Not me. I tried with an existing account.

**Comment by tauil** [comment] 2015-11-11 03:21
@lucianosousa , @viniciussbs and @aoqfonseca please, take a look at my PR to fix and close this issue ASAP.

**Comment by lucianosousa** [comment] 2015-11-15 23:39
@igorsantos07 @fnando We just deployed a new version trying fix this bug.
Can you guys take a look at it?

**Comment by tauil** [comment] 2015-11-16 11:37
Just tested and worked for me. My e-mail was unconfirmed and I had to resent the confirmation e-mail.

**Comment by lucianosousa** [comment] 2015-12-08 17:07
Closing since looks fine. If we need, it can be open again.

**Closed by lucianosousa** 2015-12-08 17:07 UTC
Labels: bug
